### ISSUE TITLE
Add an Open Source License

### ISSUE THREAD

**Issue by zicklag** [sh-dave/kex-vox-iron#1]
Hi @sh-dave, good work on this library. :smiley: I'm trying to use it to build a [sandbox demo](http://forums.armory3d.org/t/voxel-sandbox-game-for-qub3d-group/1648?u=zicklag) game. Could you please add an Open Source license to this project and your other related repos?

**Comment by sh-dave** [comment]
I think all my stuff should already have the `zlib` license in the [haxelib.json](https://github.com/sh-dave/kex-vox-iron/blob/master/haxelib.json#L4).

**Comment by zicklag** [comment]
Oh, my bad. I missed it. I was looking for a LICENSE or COPYING file. Didn't think to look in the `haxelib.json`. Thanks. :slightly_smiling_face:

**Comment by sh-dave** [comment]
Also added a separate license file in https://github.com/sh-dave/kex-vox-iron/commit/a3e253bfa1c845a046ef2fdb1cb1c5ae4866ebd1 now.
